import Navbar from "@/components/Navbar";

import { Footer } from "@/components/Footer";
import TawkToMessenger from "@/components/Tawkto";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "Essay Help",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex">
          <Navbar />
        </div>

        {children}
        <Footer />
        <TawkToMessenger />
      </body>
    </html>
  );
}
