import Navbar from '@/components/Navbar'

import { Footer } from '@/components/Footer';
import TawkToMessenger from '@/components/Tawkto';
import './globals.css';

export const metadata = {
  title: 'Essay Help',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className='flex'>
      <Navbar/>
      </div>
      
      {children}
      <Footer />
      <TawkToMessenger />        
      
      </body>
    </html>
  )
}
